dist: trusty
# trusty requires virtualization, which is set by 'sudo: required'
sudo: required
os:
    - linux
cache:
    timeout: 1000
    directories:
        - cs/packages
        - $HOME/.ccache
        - $HOME/.stack
services:
    - docker
env:
    - FLAVOR="cs"
    - FLAVOR="cpp-core" BOOST="1.66.0" COMPILER="clang"
    - FLAVOR="cpp-grpc" BOOST="1.66.0" COMPILER="clang"
    - FLAVOR="hs"
    - FLAVOR="java"

    - FLAVOR="cpp-core" BOOST="1.65.1" COMPILER="clang" CRON_ONLY="true"
    - FLAVOR="cpp-core" BOOST="1.64.0" COMPILER="clang" CRON_ONLY="true"
    - FLAVOR="cpp-core" BOOST="1.63.0" COMPILER="clang" CRON_ONLY="true"
    - FLAVOR="cpp-core" BOOST="1.62.0" COMPILER="clang" CRON_ONLY="true"
    - FLAVOR="cpp-core" BOOST="1.61.0" COMPILER="clang" CRON_ONLY="true"

    - FLAVOR="cpp-grpc" BOOST="1.65.1" COMPILER="clang" CRON_ONLY="true"
    - FLAVOR="cpp-grpc" BOOST="1.64.0" COMPILER="clang" CRON_ONLY="true"
    - FLAVOR="cpp-grpc" BOOST="1.63.0" COMPILER="clang" CRON_ONLY="true"
    - FLAVOR="cpp-grpc" BOOST="1.62.0" COMPILER="clang" CRON_ONLY="true"
    - FLAVOR="cpp-grpc" BOOST="1.61.0" COMPILER="clang" CRON_ONLY="true"

    - FLAVOR="cpp-core" BOOST="1.66.0" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-core" BOOST="1.65.1" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-core" BOOST="1.64.0" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-core" BOOST="1.63.0" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-core" BOOST="1.62.0" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-core" BOOST="1.61.0" COMPILER="gcc" CRON_ONLY="true"

    - FLAVOR="cpp-grpc" BOOST="1.66.0" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-grpc" BOOST="1.65.1" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-grpc" BOOST="1.64.0" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-grpc" BOOST="1.63.0" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-grpc" BOOST="1.62.0" COMPILER="gcc" CRON_ONLY="true"
    - FLAVOR="cpp-grpc" BOOST="1.61.0" COMPILER="gcc" CRON_ONLY="true"

    - FLAVOR="cpp-grpc-master" BOOST="1.66.0" COMPILER="clang" CRON_ONLY="true"
script:
    - if [ "$CRON_ONLY" = "true" ] && [ "$TRAVIS_EVENT_TYPE" != "cron" ] ; then echo "Skipping cron-only job"; exit 0; fi
    - CI_BUILD_IMAGE=bondciimages.azurecr.io/ubuntu-1604:build-24985895
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo "Hardware:"; grep model\ name /proc/cpuinfo | uniq -c; free -m; fi
    - time travis_retry docker pull $CI_BUILD_IMAGE
    - docker images # Dump the image ID
    - docker run -v $HOME/.ccache:/root/.ccache -v $HOME/.stack:/root/.stack -v `pwd`:/root/bond $CI_BUILD_IMAGE $HOME $FLAVOR $BOOST $COMPILER
    # docker runs as root and may leave files in the following directories that are not readable by the travis user
    - sudo chown -R travis:travis $HOME/.ccache $HOME/.stack `pwd`
