language: csharp
os: 
    - linux
    - osx

before_install:
    - echo $TRAVIS_OS_NAME
    - export CC=clang
    #linux prereqisite packages
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:boost-latest/ppa -y; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:hvr/ghc -y; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y cmake cmake-data make libboost1.55-all-dev cabal-install-1.22 ghc; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CABAL_PATH=/opt/cabal/1.22/bin; fi
    #OS X prerequisite packages
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ghc cabal-install; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -s -o mono.pkg http://download.mono-project.com/archive/3.12.0/macos-10-x86/MonoFramework-MDK-3.12.0.macos10.xamarin.x86.pkg; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo installer -pkg "mono.pkg" -target /; fi
    #show versions of cmake and clang
    - cmake --version && clang --version
    #nuget installation
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install nuget && export NUGET=nuget; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -s -o "cs/nuget/nuget.exe" -L "http://www.nuget.org/nuget.exe" && export NUGET="mono cs/nuget/nuget.exe"; fi
    #cabal-install from ppa is installed into /opt
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then /opt/cabal/1.22/bin/cabal update; else cabal update; fi

before_script:
    #restore nuget packages for solution
    - $NUGET restore cs/cs.sln

script:
    - mkdir build && cd build
    - cmake ..
    #linux build is throwed out by out of memory or travis timeout with "make check" so do only make
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make; else make --jobs 2 check; fi
    - sudo make install
    - cd ../cs
    - xbuild /p:Configuration=Release cs.sln
    #to enable unit-testing we need to convert tests from MSTest to NUnit 
    #- nunit-console <list_of_test_dlls>
