dist: trusty
# trusty requires virtualization, which is set by 'sudo: required'
sudo: required
os:
    - linux
cache:
    directories:
        - cs/packages
        - $HOME/.ccache
        - $HOME/.stack
        - $HOME/docker-images
services:
    - docker
env:
    - FLAVOR="cs"
    - FLAVOR="cpp-core" BOOST="1.65.1" COMPILER="gcc"
    - FLAVOR="cpp-core" BOOST="1.64.0" COMPILER="clang"
    - FLAVOR="cpp-core" BOOST="1.63.0" COMPILER="clang"
    - FLAVOR="cpp-core" BOOST="1.62.0" COMPILER="clang"
    - FLAVOR="cpp-core" BOOST="1.61.0" COMPILER="clang"
    - FLAVOR="cpp-core" BOOST="1.60.0" COMPILER="clang"
    - FLAVOR="cpp-core" BOOST="1.59.0" COMPILER="clang"
    - FLAVOR="cpp-core" BOOST="1.58.0" COMPILER="clang"
    - FLAVOR="cpp-comm" BOOST="1.63.0" COMPILER="clang"
    - FLAVOR="cpp-grpc" BOOST="1.65.1" COMPILER="gcc"
    - FLAVOR="cpp-grpc" BOOST="1.64.0" COMPILER="clang"
    - FLAVOR="cpp-grpc" BOOST="1.63.0" COMPILER="clang"
    - FLAVOR="hs"
    - FLAVOR="java"

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo "Hardware:"; grep model\ name /proc/cpuinfo | uniq -c; free -m; fi
    - pushd $HOME/docker-images
    - travis_retry wget -N https://bondbinaries.blob.core.windows.net/bondbinaries/docker-images/bond-xenial.tar.gz
    - popd
    - time docker load -i $HOME/docker-images/bond-xenial.tar.gz

script:
    - docker run -v $HOME/.ccache:/root/.ccache -v $HOME/.stack:/root/.stack -v `pwd`:/root/bond bond-xenial $HOME $FLAVOR $BOOST $COMPILER
